version: '3'

services:
  webserver:
    init: true
    build:
      context: build/web
      dockerfile: Dockerfile
    links:
      - database
    ports:
      - "8081:80"
    env_file:
      - .env
    volumes:
      - ./config/web/config.php:/var/www/html/config.php:ro
    depends_on:
      - database
  database:
    image: mariadb:latest
    container_name: "${COMPOSE_PROJECT_NAME}-db"
    restart: "always"
    init: true
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./config/initdb:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ${dbname}
      MYSQL_USER: ${dbuser}
      MYSQL_PASSWORD: ${dbpass}
  
  parselog:
    init: true
    restart: always
    build:
      context: build/parselog
      dockerfile: Dockerfile
    links:
      - database
    env_file:
      - .env
    volumes:
      - ./config/parselog/config.php:/usr/local/bin/parselog/config.php:ro
      - ./config/parselog/crontab:/etc/crontab:ro
      - /var/log/asterisk:/var/log/asterisk:ro
    tty: true
    depends_on:
      - database